// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using attivitaUniversitarie.Data;

#nullable disable

namespace attivitaUniversitarie.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("attivitaUniversitarie.Models.Attivita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("descrizione")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("idUser")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("scadenza")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("stato")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("titolo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("idUser");

                    b.ToTable("Attivita");
                });

            modelBuilder.Entity("attivitaUniversitarie.Models.User", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("attivitaUniversitarie.Models.Attivita", b =>
                {
                    b.HasOne("attivitaUniversitarie.Models.User", "User")
                        .WithMany("Attivita")
                        .HasForeignKey("idUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("attivitaUniversitarie.Models.User", b =>
                {
                    b.Navigation("Attivita");
                });
#pragma warning restore 612, 618
        }
    }
}
